### ISSUE TITLE
Best practices for securely properties

### ISSUE THREAD

**Issue by godfroidt** [benbahrenburg/Securely#11]
Hi,

I have played a bit with the securely module (on iOS) and it's *very* nice. Thanks for sharing this.

That being said, I have a question.  

My app, like most apps, requires a password at first use and then does not require it again (unless you logout).  
Which means, unless I am completely off mark, that the `secret` key used for `securely.createProperties()`must be hard coded in my js code (since I don't want to prompt for a password again). In turns, this means that all instances of my app share the same secret. 

Do we consider this safe by relying on obfuscation/encryption done by the Ti framework or is there something obvious I am missing ?  

My idea at this point is to generate a guid and hardcode it my source.  But if you have any best practice to share I am very interested.  I have looked around the Q&A forum etc and I haven't seen anything on this so I am wondering if I am missing something.

I am also interested to know how you go about detecting an application reinstallation, btw. So far as I can see, I can just use a regular Ti.API.Properties with a boolean firstrun properties since that properties file will get cleared up at uninstall time.  Anything better ?

Thanks again for a great module.
--T

**Comment by joshualambert** [comment]
Bump. I'm also curious as to the best practice for this, as I may be using this in my storage.js CommonJS module to provide encryption.

**Comment by benbahrenburg** [comment]
You might want to consider using a remote SSL cert or another remotely hosted key.  This provides the most secure option.
