### ISSUE TITLE
securityLevel not provided, a default of MED will be used

### ISSUE THREAD

**Issue by HPieters** [benbahrenburg/Securely#12]
For some reason I keep getting the following error when using securely on iOS?

[ERROR] securityLevel not provided, a default of MED will be used
[ERROR] A secret is required for MED and HIGH securityLevel
[ERROR] Since no secret provided BUNDLE ID will be used
[ERROR] The identifier parameter is required for KeyChain Storage
[ERROR] Since identifier was not provided BUNDLE ID will be used

I use the following code:

` var securely = require('bencoding.securely');

var properties = securely.createProperties({
    identifier: "application",
    accessGroup: "accessGroup",
    secret: "my_secret",
    storageType: securely.PROPERTY_TYPE_KEYCHAIN,
    securityLevel: securely.PROPERTY_SECURE_LEVEL_MED
});`

Am I doing anything wrong? My application still works and is able to work with the value I set.

**Comment by developer82** [comment]
Hi,

Found this thread after facing the same issue. I'm using iPhone module.

**Comment by benbahrenburg** [comment]
@developer82 use the above gist in the thread. If that doens't work, post your code and specific problem.
