### ISSUE TITLE
Cannot decrypt StringCrypto strings created by AppStore version in Ad-Hoc build on iPhone 5S+

### ISSUE THREAD

**Issue by sttts** [benbahrenburg/Securely#29]
We experience incompatibilities between encrypted strings which were created using StringCrypto inside AppStore version of our app and Ad-Hoc builds. This only happens on devices from iPhone 5S upwards.

The relevant code is
```javascript
securely.createStringCrypto().AESEncrypt(password, text, false);
```
and
```javascript
securely.createStringCrypto().AESDecrypt(password, encrypted, false);
```

Between AppStore releases of the app the encryption+decryption works. Between AppStore and Ad-Hoc builds it doesn't.

We checked that in Ad-Hoc builds, the resulting encrypted text is compatible with other libraries like OpenSSL with AES-256 and IV=0000000000000000. So we assume that in production AppStore builds something happens that results in non-standard encryption.

As far as we could find out iPhone 5S is the first device with hardware accelerated AES in CBC mode.

We have other code using the XPlatformCrypto routines, which implicitly uses non-zero IVs. This code works fine also between AppStore and Ad-Hoc.

Our app does not support 64 bits yet. So data type issues shouldn't be a problem (yet).

**Comment by sttts** [comment]
"cannot decrypt" means that decryption results in binary garbage which is expected to be json text, i.e. UTF8 encoded. Hence, the AESDecrypt method decrypts the string, but the UTF8 conversion fails, leading to a `null` return value of AESDecrypt.

**Comment by rborn** [comment]
Hey Ben, any idea on this? Stefan works with me on this project :)

Thank you.

**Comment by parijatsahai** [comment]
Any progress on this issue?

**Comment by benbahrenburg** [comment]
You can do this passing in your own IV. See this for details https://github.com/benbahrenburg/Securely/blob/master/iOS/Classes/BencodingSecurelyXPlatformCryptoProxy.m#L303

**Comment by parijatsahai** [comment]
Hi Ben, can you please elaborate on the above comment "passing in your own IV"? How do we do that? Does it require modifying the iOS class and recompiling the module or is it a parameter to be passed to the AESEncrypt and AESDecrypt methods? I apologize I don't quite understand the iOS code that you referred to.
