### ISSUE TITLE
Versioning with letter causes Ti buld to crash

### ISSUE THREAD

**Issue by ndastur** [benbahrenburg/Securely#30]
Hi Ben,
Sort of a Appc problem but with the new 4.0.0.GA SDK and alloy 1.6.0 the module versioning using a letter at the end 1.53.B causes a longjohn.js exception. Moving the directory to 1.53.2 for example fixes the problem. I am posting here as alot of other modules do keep the convention of numbers rather than letters and I suspect it is easier for you to fix. Tell me if you think this should be post to the Appc JIRA page.
Thanks

**Comment by benbahrenburg** [comment]
updated in the latest release
