### ISSUE TITLE
createPlatform and createLockScreenHelper classes not available in iOS

### ISSUE THREAD

**Issue by jaichandra** [benbahrenburg/Securely#33]
Hi Ben,

I was trying the below code

var lockHelper = securely.createLockScreenHelper();
lockHelper.startMonitorForScreenOff();
lockHelper.startMonitorForScreenOn();

This works find in Android, but doesn't work on iOS. Looks like these methods doesn't exist in iOS.
I am trying to monitor device lock/unlock states so that a specific action can be taken. Can you suggest how to get this to work in iOS and there is any alternate approaches.

Thanks
Jai

**Comment by benbahrenburg** [comment]
Without jailbreaking there isn't any reliable way to perform this check.  My only suggestion is you can create a module or fork security to create a keychain element that would be locked when device is locked and then check against that.
