### ISSUE TITLE
Access Group and Identifier doesn't work for Android

### ISSUE THREAD

**Issue by usama33** [benbahrenburg/Securely#36]
Amazing module but I am trying to share key value pairs between two apps. For that I am using the same identifier and access group with fix secret value and that works perfectly fine for iOS but it doesn't work on Android.

Any chance of how to do it or its not yet compatible?

**Comment by benbahrenburg** [comment]
I would recommend using the High level https://gist.github.com/benbahrenburg/5a8a25e7aa518ba55bd4  for saving data.  This will not be cross platform but will be most secure. Then using a common secret and the XPlatform crypto functions https://github.com/benbahrenburg/Securely/tree/master/Samples/XPlatformCrypto exchange the encrypted values between devices or your service.

In a nutshell, use the strongest encryption on device, and use XPlatform crypto between devices.
