### ISSUE TITLE
Keychain with same access group and identifier not working on iOS device

### ISSUE THREAD

**Issue by usama33** [benbahrenburg/Securely#37]
Hi,

I am initialising keychain for iOS in following way: I have three apps with following bundle IDs (I have changed real IDs with fake one)

App 1: com.myapps.mobile.first
App 2: com.myapps.mobile.second
App 3: com.myapps.mobile.third

Following is the snippet for iOS

// Open Keychain Access
var KeychainAccess = Securely.createProperties({
	    encryptFieldNames: true,
	    identifier: 'com.myapps.mobile',
	    accessGroup: 'MySecretAccessGroup',
	    secret: Ti.Utils.md5HexDigest('MySecretAccessGroup'),
	    storageType: Securely.PROPERTY_TYPE_KEYCHAIN,
	    securityLevel: Securely.PROPERTY_SECURE_LEVEL_MED
});

This works perfectly fine in iOS simulator. The key value pairs are correctly shared. However, when I deploy in device. It doesn't share. I thought may be its happening because of the passcode so I removed passcode and checked, same results.

I am using Titanium SDK 3.2.2.GA and bencoding ios module 1.53.B.

Simulator Version: 7.1
Device iOS Version: 8.1.4

**Comment by usama33** [comment]
I checked the build folder of iOS after its compiled and I didn't see updated identifier and access group of keychain. It's always {10DigitAppID}.{BundleID} i.e. "ABCDEFGHIJ.com.myapps.mobile.first" for App 1.

**Comment by benbahrenburg** [comment]
Correct, this isn't supported
