### ISSUE TITLE
Recover from Backup

### ISSUE THREAD

**Issue by brownemint** [benbahrenburg/Securely#41]
Hi,

Not really an issue, more or a question...
Is it possible to recover the the plist after a backup is restored? Would the syncAllowed boolean in BencodingSecurelyPropertiesProxy.m control this (if I was to modify the source myself) or am I looking in the wrong location altogether?

Regards

**Comment by benbahrenburg** [comment]
Depending on if you are using plist or keychain your ability to restore for a back-up would be different. Since keychain back-up I believe is controlled by the user I'm not sure I would try to perform a restore without being able to re-write your crypto keys.
