### ISSUE TITLE
listProperties returns undefined when storageType is PROPERTY_TYPE_PREFERENCES

### ISSUE THREAD

**Issue by parijatsahai** [benbahrenburg/Securely#43]
The properties documentation of listProperties() method says that an array of keychain properties is returned. Does it mean that the method doesn't work if the storageType is PROPERTY_TYPE_PREFERENCES?

For some reason, this method is returning undefined in iOS simulator for 5s with securityLevel being PROPERTY_SECURE_LEVEL_MED.

**Comment by benbahrenburg** [comment]
This has been removed to promote better security handling. You should see an error written that it has been removed.

**Comment by benbahrenburg** [comment]
If you need this has part of your implementation, you can fork and add. I would recommend keeping a list of your key fields elsewhere and performing direct reads though.
