### ISSUE TITLE
Question: properties persistence after App update

### ISSUE THREAD

**Issue by pakoArtal** [benbahrenburg/Securely#44]
Hi Ben,

Not an issue but a question.

After reading the [Secure Properties documentation](https://github.com/benbahrenburg/Securely/blob/master/Documentation/strings.md) and this issue [Security Properties persistence on Android platform](https://github.com/benbahrenburg/Securely/issues/2) I'm not sure yet what will happen with the stored data after an App update (Android & iOS). Will they be lost?  

I'm not sure what would happen if I just use Titanium.App.Properties.  Will they persist after App updates? 

Regards,

Pako Artal

**Comment by benbahrenburg** [comment]
It really depends on how you structure your application.  But, in general on update you should be ok. If the user deletes your application on iOS (using the keychain) your values will be saved and available if they re-install your app. On Android they will be removed when your app is removed.

As always I would recommend testing your different use cases.

**Comment by pakoArtal** [comment]
Thank you Ben!
