### ISSUE TITLE
Get "Assertion failure" error on device but the methods AESDecrypt and AESEncrypt work on simulator

### ISSUE THREAD

**Issue by parijatsahai** [benbahrenburg/Securely#46]
The encryption and decryption works fine on the Simulator but when I run the same app on the iPhone 6s Plus device via Titanium Studio (not adhoc or production install), I get the following error:
`*** Assertion failure in -[NSConcreteMutableData decryptedDataUsingAlgorithm:key:initializationVector:options:error:], /Users/benbahrenburg/Projects/Modules/Securely/iOS/Classes/AESCrypt/NSData+CommonCrypto.m:478`
I'm assuming it's related to #29 issue that Stefan brought up earlier that was closed.
Btw, I'm using the iOS dist 2.1.0.

**Comment by benbahrenburg** [comment]
@parijatsahai would recommend passing in your IV if you believe that is the problem. Otherwise would recommend loading the project into Xcode and debugging as the above could mean anything from a key error to a size related overflow.

**Comment by parijatsahai** [comment]
Please provide details on "passing in your IV" as the documentation doesn't mention "IV" as an input parameter anywhere. Also, from what I've heard elsewhere, passing in my own IV would mean I'd have to manage it as well, i.e., generate unique IV for each request and sending the IV as part of the encrypted message to the other party so that the message can be decrypted. I had hoped that this module would eliminate that issue. Or am I overthinking it?

**Comment by benbahrenburg** [comment]
@parijatsahai the module is open source so you are welcome to create a test and fix the issue you are encountering.  You can find the code to pass in the IV here https://github.com/benbahrenburg/Securely/blob/master/iOS/Classes/BencodingSecurelyXPlatformCryptoProxy.m#L303
