### ISSUE TITLE
Module not working for getting value after uninstalling app .

### ISSUE THREAD

**Issue by imranansari123** [benbahrenburg/Securely#47]
i have saved value in properties and i get the value until i did not delete app.
 **But after uninstalling app i am not getting the property which i created.**

I used the code is:-

var securely = require('bencoding.securely');

var properties = securely.createProperties({
identifier : "Foo",
accessGroup : "Bar"
});
**//Check property existance..**
var exists = properties.hasProperty('String');
Titanium.API.info('String Property ' + ((exists) ? " Exists" : " Doesn't Exist"));  
**//Print in console      "Exists"                       ---> if i am not uninstall app.    
//Print in console      "Doesn't Exist"         ----> if i uninstall app and reinstall.**  

properties.setString('String', 'I am a String Value'); //set Value
Titanium.API.info('String: ' + properties.getString('String')); //Output correct.
//Print in console      "I am a String Value"

**Comment by benbahrenburg** [comment]
You should be using the new API, check out the example here https://gist.github.com/benbahrenburg/5a8a25e7aa518ba55bd4

Please note saving after install is only available for iOS, on device.  This is due to the fact we save to the keychain.
