### ISSUE TITLE
An uncaught exception was thrown!

### ISSUE THREAD

**Issue by implicitli** [benbahrenburg/Securely#49]
Simply added module, and not doing anything with it yet, and I am getting this error.
2016-12-03T21:55:37.684Z | ERROR  | An uncaught exception was thrown!
Failed to install app on device (0xe8008016)
2016-12-03T21:55:37.685Z | ERROR  | Failed to install app on device (0xe8008016)

**I have this in tiapp.xml**
`
<dict>
     <key>keychain-access-groups</key>
     <array>
          <string>com.domain.appname</string>
     </array>
`

**added this to alloy.js**
`
var securely = require('bencoding.securely');
var platform_device = require('platform_device');		platform_device();
if (OS_IOS) {
		var properties = securely.createProperties({
			secret : "mysecrethere",
			storageType:securely.PROPERTY_TYPE_KEYCHAIN,
			securityLevel:securely.PROPERTY_SECURE_LEVEL_HIGH
		});
} else if (OS_ANDROID) {
		var properties = securely.createProperties({
			encryptFieldNames : true,
			secret : "mysecrethere",
			storageType:securely.PROPERTY_TYPE_PREFERENCES,
			securityLevel:securely.PROPERTY_SECURE_LEVEL_HIGH
		});
}
`

**and I added the file  "appname.entitlements" , into directory /app/platform/ios with this content**
`
?xml version="1.0" encoding="UTF-8"?
!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"
plist version="1.0"
<dict>
    <key>keychain-access-groups</key>
    <array>
        <string>com.domain.appname</string>
    </array>
</dict>
/plist
`

Module:  2.1.1
Ti:   5.5.1GA

**Comment by benbahrenburg** [comment]
Not really enough information to debug.  First though it sounds like the module isn't installed correctly or your configuration is incorrect.  I'd recommend downloading the source and debugging.

The latest module builds are compiled against Ti SDK 6. Would recommend upgrading to the latest as it contains updates.

**Comment by implicitli** [comment]
wow.  The issue was AppC Studio had apparently timed out my session.  Simply ran appc login, cleaned build and it worked.

Module works great!  Awesome work - thanks for your contribution.

**Comment by benbahrenburg** [comment]
Great, glad everything is working
