### ISSUE TITLE
Android persistent storage using 'properties'

### ISSUE THREAD

**Issue by implicitli** [benbahrenburg/Securely#50]
on iOS, my view loads and retrieves the emailAddress saved from a previous session just fine.

on Android, the value is null - it is not saving once the app is closed.

config:
`
if (OS_IOS) {
		var properties = securely.createProperties({
			secret : "SECRET_HERE_REMOVED",
			storageType:securely.PROPERTY_TYPE_KEYCHAIN,
			securityLevel:securely.PROPERTY_SECURE_LEVEL_HIGH
		});
} else if (OS_ANDROID) {
		var properties = securely.createProperties({
			encryptFieldNames : true,
			secret : "SECRET_HERE_REMOVED",
			storageType:securely.PROPERTY_TYPE_PREFERENCES,
			securityLevel:securely.PROPERTY_SECURE_LEVEL_HIGH
		});
}
`

Setter:
properties.setString('myEmail', advanceAuth.Result.EmailAddress);

Getter:
$.emailAddress.value = properties.getString('myEmail');

Why is this only an issue on Android?  Is there some Android permission I need to include in my tiapp.xml?

Thanks,
Adam.

**Comment by implicitli** [comment]
ok, it seems this is the issue.  It seems 'hasProperty' is not working on Android.

in alloy.js I am running this to validate that the property exists before attempting to retrieve and populate the textfield.  And on first startup, then it would create a null value, otherwise if not first login, simply ignore and move on.

This works perfect on iOS, but on Android it is not finding the property and therefore setting to null.

if (!properties.hasProperty('myEmail')) { properties.setString('myEmail', null); }


if I remove this line all together then my 'getter" gets the value and populates the field....so the value is there...the hasProperty method just seems to not be working on Android.

**Comment by benbahrenburg** [comment]
Thanks. Fixed in this commit.  You can recompile the module and it should be working as expected.

https://github.com/benbahrenburg/Securely/commit/97cf86942d9d61541b45531bf20b0a0d31b0c9a4
