### ISSUE TITLE
Question about passphrase

### ISSUE THREAD

**Issue by kopiro** [benbahrenburg/Securely#52]
Hi - great module!

I've a question about the passphrases used for the method `createProperties `. 
Where should I store it?

I imagined these things:
- set statically in the tiapp.xml as a property
- generate using a salt (UUID or by using `generateRandomKey`) + secret (from tiapp.xml) and store in the TiAppProperties at runtime

But, `Ti.App.Properties` uses `NSStandardDefault`that is by definition not secure. 
So... any advice?
Which is the best method?

**Comment by benbahrenburg** [comment]
Keystorage and hiding secrets can be difficult.   There is really no one answer or all cases.

I would recommend against storing any seed information in your tiapp.xml as this is often checked into source control.  And Ti.App.Properties is stored in plain text on the device. Which means your key could be detected.

In my opinion the best approach is a derived key containing something specific to the user, something specific to the device, and something from the server.    If you can only manage one of the above it is best to keep at least part of your key server side. Or if that is not possible I would explore if you can generate a key from something the user will input.

**Comment by kopiro** [comment]
Okay! But should I store this key or should I generate it everytime?
Because with your module I can only generate different keys for each call.

**Comment by benbahrenburg** [comment]
You would want to construct it each time.  This avoids someone from being able to gain access to all of the secrets your phrase secures.
