### ISSUE TITLE
Problem with android

### ISSUE THREAD

**Issue by jmosqueda1987** [benbahrenburg/Securely#53]
Hi, I love this plugin, but I've a problem with Android and PHP. In IOS the encrypt and decrypt in PHP working perfectly, but in android don't exist the "encrypt" method.

``` javascript
var encryptedText = stringCrypto.encrypt({
       password : password,
	value : qr,
	resultType : 'text',
	completed : function(e) {
	console.log(e.result);
		qrPut(e.result);
	},
});
```

This code work in IOS but don't in Android 
``` javascript
var aesEncryptedString = stringCrypto.AESEncrypt(password, qr);
``` 

The result of this method is a Hex string, but in PHP i don't know how to decrypt

Can you help me

Regards

Thanks

**Comment by benbahrenburg** [comment]
Happy to review a PR if you want to contribute.

**Comment by jmosqueda1987** [comment]
It's posible to do this modifications and asymmetrical encription/decription with a freelance payment?
