### ISSUE TITLE
pre-3.0-changes branch on 6.0.2.GA

### ISSUE THREAD

**Issue by andersondo** [benbahrenburg/Securely#54]
I'm trying to build our app with the pre-3.0-changes branch with titanium sdk version 6.0.2.GA and I'm getting the following error on build.

[ERROR] :  Found incompatible Titanium Modules:
[ERROR] :     id: bencoding.securely	 version: 3.0.9	 platform: android	 min sdk: 5.1.0.GA

Is there any way to use the old encryption with this SDK?

**Comment by benbahrenburg** [comment]
You would just need to upgrade the project to the latest Ti SDK and recompile.  Please keep in mind that a few of the Android calls used in that branch are no longer part of Android 7+.  This might mean you need to back point a few of the updates from the master branch as well.
