### ISSUE TITLE
New versions of the Android SDK no longer support the Crypto provider

### ISSUE THREAD

**Issue by adamtarmstrong** [benbahrenburg/Securely#58]
I am currently using v2.1.1 of your module.

My Implementation is very basic:
`
if (OS_IOS) {
		var properties = securely.createProperties({
			secret : "SECRET_REMOVED",
			storageType:securely.PROPERTY_TYPE_KEYCHAIN,
			securityLevel:securely.PROPERTY_SECURE_LEVEL_HIGH
		});
} else if (OS_ANDROID) {
		var properties = securely.createProperties({
			encryptFieldNames : true,
			secret : "SECRET_REMOVED",
			storageType:securely.PROPERTY_TYPE_PREFERENCES,
			securityLevel:securely.PROPERTY_SECURE_LEVEL_HIGH
		});
}
`

Today I started getting the following alert in my Titanium Console when deploying to my Android device.
********** PLEASE READ ************
*
* New versions of the Android SDK no longer support the Crypto provider.
* If your app was relying on setSeed() to derive keys from strings, you
* should switch to using SecretKeySpec to load raw key bytes directly OR
* use a real key derivation function (KDF). See advice here :
* http://android-developers.blogspot.com/2016/06/security-crypto-provider-deprecated-in.html
***********************************
Returning an instance of SecureRandom from the Crypto provider
as a temporary measure so that the apps targeting earlier SDKs
keep working. Please do not rely on the presence of the Crypto
provider in the codebase, as our plan is to delete it
completely in the future.

Have you seen this before?  What do I need to do?

Thanks,
Adam.

**Comment by benbahrenburg** [comment]
Hey Adam, 
This is fixed in master. You can compile from source and the issue will go away.  Unfortunately this is a breaking change so prior encrypted properties will no longer be readable.

**Comment by adamtarmstrong** [comment]
Thanks!

I converted my project to SDK 6.1.1GA, the properties were not readable as you stated, I re-entered my credentials, exited app, and re-entered and it retrieved them.  So it appears all code/functionality is transparent in the upgrade with no changes needed.  On the only adverse side-affect is that the user must re-enter their credentials on the first launch.

As I see it other than simply inserting the new module, and communicating the impact to the users, there is nothing else I need to do (as it relates to my app)?  Correct!?

Thanks,
Adam.

**Comment by benbahrenburg** [comment]
If you are just using SecureProperties the steps you outlined is correct.

If you are using secure strings or file encryption those would also be impacted.
