### ISSUE TITLE
Issue calling sha256 on Android

### ISSUE THREAD

**Issue by raybelisle** [benbahrenburg/Securely#59]
Using version 3.1.0, calling sha256 from Android, I get the following error:

`[ERROR] :  StringCryptoProxy: Couldn't find proxy method 'sha256' with signature '(Ljava/lang/String;)Ljava/lang/String;'`

Not sure why or how to address this.

**Comment by benbahrenburg** [comment]
Could you send me the JS you are using to make the call?  
The proxy method is in place so not sure what would be causing the issue.
https://github.com/benbahrenburg/Securely/blob/master/Android/src/bencoding/securely/StringCryptoProxy.java#L23  

I would also recommend moving to the native Ti.Utils.sha256(obj) method in the Titanium SDK.  This removes a crossing dependency and is optimized by the Ti SDK

You can read about the Ti SDK method here:
http://docs.appcelerator.com/platform/latest/#!/api/Titanium.Utils-method-sha256

**Comment by raybelisle** [comment]
So, here is how it is being called:

`var randomKey = securely.generateRandomKey();
Ti.API.info("Random Key = " + randomKey);
randomKey = randomKey.substring(0,32);
var stringCrypto = securely.createStringCrypto();

var verifobj = Ti.Utils.base64encode(randomKey);
Alloy.Globals.APIout('verifobj: ' + verifobj);
var verifier = verifobj.toString();
verifier = verifier.replace('=','');
verifier = verifier.replace('=','');
verifier = verifier.replace(/\+/g, '-');
verifier = verifier.replace(/\//g, '_');
verifier = verifier.replace(/[^\x00-\x7F]/g, "");
Alloy.Globals.APIout('verifier: ' + verifier);
var chaltemp = stringCrypto.sha256(verifier);
Alloy.Globals.APIout('chaltemp is: ' + chaltemp);
`
It only fails on the sha256 call on Android, on iOS it works fine. I didn't realize there was an sha256 method in Ti.utils. Just switched to that and it seemed to work. So, not needed for now, but still weird that it fails when I call the sha256 method of your module.

Thanks for the help
