### ISSUE TITLE
Setup properties without secret ?

### ISSUE THREAD

**Issue by dx777** [benbahrenburg/Securely#61]
Hi, i'm currently converting an App, from Titanium to native Swift.
I was able to get key:value, from the keychain, which was encoded with your framework, with the following parameters: 
```
    var properties = Alloy.Globals.Securely.createProperties({
        identifier: "myappidentifier",
        accessGroup: Alloy.Globals.SuiteName,
        storageType: Alloy.Globals.Securely.PROPERTY_TYPE_KEYCHAIN,
        securityLevel: Alloy.Globals.Securely.PROPERTY_SECURE_LEVEL_HIGH
    });
```
The hashes are in that format:
key:
`099d64484e158b90c000e144cff76cfb2548cf1e17b8d8bf319b480d71bf27bfedf92b41048d88e2dbf8c6bceda15fa202f1dbf54c559c12f2e424e64e2253ab`
value:
`wnXGfwFQr4463RLAczVJGw==`

How can i decode it ? 
Thank you.

**Comment by benbahrenburg** [comment]
You are correct the module does more than just use the secret to encrypt.  What you are looking to do is pretty easy.  Simply look through the code and see how the secret is generated for your user case.  Then you will need to use the same crypto calls in Swift to decrypt.

**Comment by dx777** [comment]
How do i look through source code, if it's all inside libbencoding.securely.a ?

**Comment by benbahrenburg** [comment]
Everything you need is in this github repo. If you are new to programming you can look in the https://github.com/benbahrenburg/Securely/tree/master/iOS directory for all of the iOS Titanium code for the module.
